apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: clusterresourceoverrides.admission.autoscaling.openshift.io
  labels:
    clusterresourceoverride: "true"
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: clusterresourceoverrides.admission.autoscaling.openshift.io
    namespaceSelector:
      matchLabels:
        clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: "true"
      matchExpressions:
        - key: runlevel
          operator: NotIn
          values: ["0","1"]
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: kubernetes 
        namespace: default
        path: /apis/admission.autoscaling.openshift.io/v1/clusterresourceoverrides
      caBundle: ""
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
        scope: "Namespaced"
    failurePolicy: Fail
    timeoutSeconds: 5
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions: ["v1"]
